# Allwinner H618
LINUXFAMILY="sun50iw9"
BOARD_NAME="LubanCat-A1CS"
UBOOT_CONFIG="lubancat_a1_defconfig"
LINUX_CONFIG="linux_h618_defconfig"
LINUX_DTB_NAME="sun50iw9-lubancat-iotest"
# KERNEL_TARGET="current,next"
KERNEL_TARGET="current"
DISTRIB_TYPE_CURRENT="bullseye jammy"
DISTRIB_TYPE_NEXT="bullseye bookworm jammy"
REVISION="1.$(date +%g%m)stable"
